### ISSUE TITLE
i8 being interpreted as char in Vec

### ISSUE THREAD

**Issue by xyven1** [cmrschwarz/rust-prettifier-for-lldb#2]
What the title says. When inspecting a vector of `i8` values, lldb shows them as `char` values, which is not optimal. 
As rendered by dapui in nvim:
![image](https://github.com/user-attachments/assets/229399be-6137-438b-800a-43b6b67a3dbf)
The type as given by rust-analyzer:
![image](https://github.com/user-attachments/assets/7f4a05c8-9df8-4714-96d4-9f16d4aad2b3)

**Comment by cmrschwarz** [comment]
I partially fixed this in #3 , to the point where the summary should be correct and you should see
the integer value in the details. 

Could I ask you to try the new build and report if that improves your usecase?

Unfortunately the char value will still be displayed aswell (you now have both) in the details.
I tried around quite a bit but found no way of changing that,
So I just tried my best to make it at least usable.
